discord:
  token: ENC(rOGfByHxay5VcIMWlRjywRXZnu0lOs/+1FCwC9IoR6aMV8ne69tCkVsAQmuB/mcfiJph+z7ClJqk4YGinTS82mrFRF6IhVT8K66N5m+rmFdsS9N4vlwIFjf0FPdXoyRE)
  selfname: "javibot-DEV"
bot:
  tellTurnsOnStartup: false